#!/usr/bin/env bash
# scripts/contribute-to-harness.sh
#
# HARNESS_FEEDBACK.md와 새 LESSON 파일을 harness-template에 PR로 자동 전송합니다.
#
# 사전 조건:
#   git remote add harness <harness-template-url>   # 최초 1회
#   gh auth login                                    # gh CLI 인증
#
# 사용법:
#   bash scripts/contribute-to-harness.sh            # PR 생성
#   bash scripts/contribute-to-harness.sh --dry-run  # 내용 확인만 (PR 생성 안 함)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PROJECT_NAME="$(basename "$REPO_ROOT")"
DATE="$(date +%Y-%m-%d)"
DRY_RUN=false

# 소스 프로젝트의 harness 버전 읽기
HARNESS_VERSION=""
if [ -f "$REPO_ROOT/HARNESS_VERSION" ]; then
    HARNESS_VERSION="$(tr -d '[:space:]' < "$REPO_ROOT/HARNESS_VERSION")"
fi
VERSION_SUFFIX="${HARNESS_VERSION:+-v${HARNESS_VERSION}}"
BRANCH_NAME="contrib/from-${PROJECT_NAME}${VERSION_SUFFIX}-${DATE}"

[ "${1:-}" = "--dry-run" ] && DRY_RUN=true

# 종료 시 임시 디렉토리 정리
TMPDIR_HARNESS=""
cleanup() { [ -n "$TMPDIR_HARNESS" ] && rm -rf "$TMPDIR_HARNESS"; }
trap cleanup EXIT

echo "🔍 사전 확인 중..."

if ! git -C "$REPO_ROOT" remote get-url harness &>/dev/null; then
    echo "❌ 'harness' remote가 등록되지 않았습니다."
    echo "   git remote add harness <harness-template-url>"
    exit 1
fi

if ! command -v gh &>/dev/null; then
    echo "❌ gh CLI가 필요합니다: https://cli.github.com"
    exit 1
fi

HARNESS_URL="$(git -C "$REPO_ROOT" remote get-url harness)"

# --- 기여할 내용 수집 ---
FEEDBACK_FILE="$REPO_ROOT/HARNESS_FEEDBACK.md"
FEEDBACK_HAS_ITEMS=false
grep -q '^\- \[' "$FEEDBACK_FILE" 2>/dev/null && FEEDBACK_HAS_ITEMS=true

LESSON_FILES=()
while IFS= read -r f; do
    [[ "$f" == *"LESSON-TEMPLATE.md" ]] && continue
    LESSON_FILES+=("$f")
done < <(find "$REPO_ROOT/docs/lessons" -name "LESSON-[0-9]*.md" 2>/dev/null | sort)

if [ "$FEEDBACK_HAS_ITEMS" = false ] && [ ${#LESSON_FILES[@]} -eq 0 ]; then
    echo "ℹ️  기여할 내용이 없습니다."
    echo "   HARNESS_FEEDBACK.md에 항목을 작성하거나 docs/lessons/에 LESSON 파일을 추가하세요."
    exit 0
fi

echo ""
echo "📋 기여 항목:"
[ "$FEEDBACK_HAS_ITEMS" = true ] && echo "  ✓ HARNESS_FEEDBACK.md"
for f in "${LESSON_FILES[@]}"; do
    echo "  ✓ docs/lessons/$(basename "$f")"
done
echo ""
echo "  브랜치: $BRANCH_NAME"
echo "  대상:   $HARNESS_URL"
[ -n "$HARNESS_VERSION" ] && echo "  버전:   v${HARNESS_VERSION}"
echo ""

if [ "$DRY_RUN" = true ]; then
    echo "🔎 dry-run 모드 — 실제 PR은 생성되지 않습니다."
    exit 0
fi

# --- harness-template 임시 클론 ---
TMPDIR_HARNESS="$(mktemp -d)"
echo "⬇️  harness-template 클론 중..."
git clone --depth=1 "$HARNESS_URL" "$TMPDIR_HARNESS" -q

cd "$TMPDIR_HARNESS"

# 동일 브랜치 중복 방지
if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
    echo "⚠️  브랜치 '$BRANCH_NAME'가 이미 원격에 존재합니다."
    echo "   오늘 이미 PR을 생성했거나, 해당 브랜치 삭제 후 재시도하세요."
    exit 1
fi

git checkout -b "$BRANCH_NAME" -q

# --- 파일 복사 ---
FILES_TO_STAGE=()
if [ "$FEEDBACK_HAS_ITEMS" = true ]; then
    cp "$FEEDBACK_FILE" "$TMPDIR_HARNESS/HARNESS_FEEDBACK.md"
    FILES_TO_STAGE+=("HARNESS_FEEDBACK.md")
fi
for f in "${LESSON_FILES[@]}"; do
    cp "$f" "$TMPDIR_HARNESS/docs/lessons/$(basename "$f")"
    FILES_TO_STAGE+=("docs/lessons/$(basename "$f")")
done

git add "${FILES_TO_STAGE[@]}"
git commit -m "contrib(from-${PROJECT_NAME}): feedback and lessons ${DATE}" -q

echo "⬆️  브랜치 push 중..."
git push origin "$BRANCH_NAME" -q

# --- PR 본문 생성 ---
LESSON_LIST=""
for f in "${LESSON_FILES[@]}"; do
    LESSON_LIST="${LESSON_LIST}"$'\n'"- \`docs/lessons/$(basename "$f")\`"
done

FEEDBACK_LINE=""
[ "$FEEDBACK_HAS_ITEMS" = true ] && FEEDBACK_LINE=$'\n'"- \`HARNESS_FEEDBACK.md\`"

VERSION_LINE=""
[ -n "$HARNESS_VERSION" ] && VERSION_LINE=$'\n'"**기반 harness 버전**: \`v${HARNESS_VERSION}\`"

PR_BODY="## From project: \`${PROJECT_NAME}\`
${VERSION_LINE}

### 포함 파일
${FEEDBACK_LINE}${LESSON_LIST}

### 반영 가이드
- \`HARNESS_FEEDBACK.md\` → Template 수정 제안 항목을 해당 docs 파일에 적용
- LESSON 파일 → \`docs/lessons/\`에 추가 후 관련 docs 수정

---
🤖 Generated by \`scripts/contribute-to-harness.sh\` from \`${PROJECT_NAME}\`"

echo "📬 PR 생성 중..."
PR_URL="$(gh pr create \
    --title "contrib(from-${PROJECT_NAME}): harness feedback ${DATE}" \
    --body "$PR_BODY" \
    --base main)"

echo ""
echo "✅ PR 생성 완료: $PR_URL"
